==6938== Memcheck, a memory error detector
==6938== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==6938== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==6938== Command: ./interpret ./Testy//OTHER_TESTS/notinitialized.test
==6938== Parent PID: 6878
==6938== 
==6938== 
==6938== HEAP SUMMARY:
==6938==     in use at exit: 0 bytes in 0 blocks
==6938==   total heap usage: 171 allocs, 171 frees, 18,666 bytes allocated
==6938== 
==6938== All heap blocks were freed -- no leaks are possible
==6938== 
==6938== For counts of detected and suppressed errors, rerun with: -v
==6938== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
