==8762== Memcheck, a memory error detector
==8762== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==8762== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==8762== Command: ./interpret ./Testy/SEM_TESTS/test_sem4.test
==8762== Parent PID: 8646
==8762== 
==8762== 
==8762== HEAP SUMMARY:
==8762==     in use at exit: 0 bytes in 0 blocks
==8762==   total heap usage: 208 allocs, 208 frees, 19,646 bytes allocated
==8762== 
==8762== All heap blocks were freed -- no leaks are possible
==8762== 
==8762== For counts of detected and suppressed errors, rerun with: -v
==8762== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
