==13123== Memcheck, a memory error detector
==13123== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==13123== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==13123== Command: ./interpret ./Testy/test_lex2.test
==13123== Parent PID: 13073
==13123== 
==13123== 
==13123== HEAP SUMMARY:
==13123==     in use at exit: 0 bytes in 0 blocks
==13123==   total heap usage: 129 allocs, 129 frees, 17,099 bytes allocated
==13123== 
==13123== All heap blocks were freed -- no leaks are possible
==13123== 
==13123== For counts of detected and suppressed errors, rerun with: -v
==13123== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
