chyby:
    ./Testy/ERROR_TESTS/sem_error10
            return value: 2
            expected raturn value: 3

    ./Testy/ERROR_TESTS/sem_error11
            Actual return value: 2
            Expected return value: 4

    ./Testy/ERROR_TESTS/sem_error12
            Actual return value: 0
            Expected return value: 3

    ./Testy/ERROR_TESTS/sem_error6
            Actual return value: 3
            Expected return value: 4

    ./Testy/ERROR_TESTS/synt_error15
            Actual return value: 3
            Expected return value: 2

    ./Testy/OTHER_TESTS/divisionbyzero
      |     in use at exit: 18,886 bytes in 238 blocks
      |   total heap usage: 279 allocs, 41 frees, 23,251 bytes allocated
      |    definitely lost: 0 bytes in 0 blocks
      |    indirectly lost: 0 bytes in 0 blocks
      |      possibly lost: 0 bytes in 0 blocks
      |    still reachable: 18,886 bytes in 238 blocks
      |         suppressed: 0 bytes in 0 blocks

    ./Testy/SYN_TESTS/test_syn1
      |  Address 0x520dd00 is 0 bytes inside a block of size 56 free'd
      |  Address 0x520df68 is 40 bytes inside a block of size 48 free'd
      |     in use at exit: 0 bytes in 0 blocks
      |   total heap usage: 517 allocs, 517 frees, 29,603 bytes allocated
