==5363== Memcheck, a memory error detector
==5363== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==5363== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==5363== Command: ./interpret ./Testy/LEX_TESTS/test_lex3.test
==5363== Parent PID: 5278
==5363== 
==5363== 
==5363== HEAP SUMMARY:
==5363==     in use at exit: 0 bytes in 0 blocks
==5363==   total heap usage: 112 allocs, 112 frees, 16,778 bytes allocated
==5363== 
==5363== All heap blocks were freed -- no leaks are possible
==5363== 
==5363== For counts of detected and suppressed errors, rerun with: -v
==5363== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
